# Generated by Django 3.0.10 on 2020-09-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('compoany_logo', models.ImageField(upload_to='media/cv/jobs/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.DecimalField(decimal_places=1, max_digits=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school_logo', models.ImageField(upload_to='media/cv/education/')),
                ('order', models.IntegerField(null=True, unique=True)),
                ('disabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/cv/info')),
                ('description', models.CharField(max_length=100)),
                ('order', models.IntegerField(null=True, unique=True)),
                ('disabled', models.BooleanField(default=True)),
                ('icon_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/cv/skills')),
                ('order', models.IntegerField(null=True, unique=True)),
                ('disabled', models.BooleanField(default=False)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('order', models.IntegerField(null=True, unique=True)),
                ('disabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('certificat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('certificat_img', models.ImageField(blank=True, null=True, upload_to='media/cv/courses')),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(null=True, unique=True)),
                ('disabled', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Provider')),
            ],
        ),
    ]
