# Generated by Django 3.0.10 on 2020-09-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200903_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/cv/projects')),
                ('order', models.IntegerField(null=True, unique=True)),
                ('disabled', models.BooleanField(default=True)),
                ('technologies', models.ManyToManyField(to='cv.Skill')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
