# Generated by Django 3.0.10 on 2020-09-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200903_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/cv/social')),
                ('order', models.IntegerField(null=True, unique=True)),
                ('disabled', models.BooleanField(default=True)),
                ('icon_code', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
